// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_listenfy/test/video_player_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_listenfy/app/data/local/local_library_store.dart'
    as _i7;
import 'package:flutter_listenfy/app/models/media_item.dart' as _i4;
import 'package:flutter_listenfy/app/models/subtitle_track.dart' as _i5;
import 'package:flutter_listenfy/app/services/video_service.dart' as _i3;
import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRx_0<T> extends _i1.SmartFake implements _i2.Rx<T> {
  _FakeRx_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_1 extends _i1.SmartFake implements _i2.RxBool {
  _FakeRxBool_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxDouble_2 extends _i1.SmartFake implements _i2.RxDouble {
  _FakeRxDouble_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxInt_3 extends _i1.SmartFake implements _i2.RxInt {
  _FakeRxInt_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxn_4<T> extends _i1.SmartFake implements _i2.Rxn<T> {
  _FakeRxn_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_5<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VideoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoService extends _i1.Mock implements _i3.VideoService {
  @override
  bool get keepLastItem =>
      (super.noSuchMethod(
            Invocation.getter(#keepLastItem),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.Rx<_i3.VideoPlaybackState> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeRx_0<_i3.VideoPlaybackState>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeRx_0<_i3.VideoPlaybackState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.Rx<_i3.VideoPlaybackState>);

  @override
  _i2.RxBool get isPlaying =>
      (super.noSuchMethod(
            Invocation.getter(#isPlaying),
            returnValue: _FakeRxBool_1(this, Invocation.getter(#isPlaying)),
            returnValueForMissingStub: _FakeRxBool_1(
              this,
              Invocation.getter(#isPlaying),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_1(this, Invocation.getter(#isLoading)),
            returnValueForMissingStub: _FakeRxBool_1(
              this,
              Invocation.getter(#isLoading),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.Rx<Duration> get position =>
      (super.noSuchMethod(
            Invocation.getter(#position),
            returnValue: _FakeRx_0<Duration>(
              this,
              Invocation.getter(#position),
            ),
            returnValueForMissingStub: _FakeRx_0<Duration>(
              this,
              Invocation.getter(#position),
            ),
          )
          as _i2.Rx<Duration>);

  @override
  _i2.Rx<Duration> get duration =>
      (super.noSuchMethod(
            Invocation.getter(#duration),
            returnValue: _FakeRx_0<Duration>(
              this,
              Invocation.getter(#duration),
            ),
            returnValueForMissingStub: _FakeRx_0<Duration>(
              this,
              Invocation.getter(#duration),
            ),
          )
          as _i2.Rx<Duration>);

  @override
  _i2.RxDouble get volume =>
      (super.noSuchMethod(
            Invocation.getter(#volume),
            returnValue: _FakeRxDouble_2(this, Invocation.getter(#volume)),
            returnValueForMissingStub: _FakeRxDouble_2(
              this,
              Invocation.getter(#volume),
            ),
          )
          as _i2.RxDouble);

  @override
  _i2.RxDouble get speed =>
      (super.noSuchMethod(
            Invocation.getter(#speed),
            returnValue: _FakeRxDouble_2(this, Invocation.getter(#speed)),
            returnValueForMissingStub: _FakeRxDouble_2(
              this,
              Invocation.getter(#speed),
            ),
          )
          as _i2.RxDouble);

  @override
  _i2.RxInt get completedTick =>
      (super.noSuchMethod(
            Invocation.getter(#completedTick),
            returnValue: _FakeRxInt_3(this, Invocation.getter(#completedTick)),
            returnValueForMissingStub: _FakeRxInt_3(
              this,
              Invocation.getter(#completedTick),
            ),
          )
          as _i2.RxInt);

  @override
  _i2.Rxn<_i4.MediaItem> get currentItem =>
      (super.noSuchMethod(
            Invocation.getter(#currentItem),
            returnValue: _FakeRxn_4<_i4.MediaItem>(
              this,
              Invocation.getter(#currentItem),
            ),
            returnValueForMissingStub: _FakeRxn_4<_i4.MediaItem>(
              this,
              Invocation.getter(#currentItem),
            ),
          )
          as _i2.Rxn<_i4.MediaItem>);

  @override
  _i2.Rxn<_i4.MediaVariant> get currentVariant =>
      (super.noSuchMethod(
            Invocation.getter(#currentVariant),
            returnValue: _FakeRxn_4<_i4.MediaVariant>(
              this,
              Invocation.getter(#currentVariant),
            ),
            returnValueForMissingStub: _FakeRxn_4<_i4.MediaVariant>(
              this,
              Invocation.getter(#currentVariant),
            ),
          )
          as _i2.Rxn<_i4.MediaVariant>);

  @override
  _i2.Rxn<String> get playbackError =>
      (super.noSuchMethod(
            Invocation.getter(#playbackError),
            returnValue: _FakeRxn_4<String>(
              this,
              Invocation.getter(#playbackError),
            ),
            returnValueForMissingStub: _FakeRxn_4<String>(
              this,
              Invocation.getter(#playbackError),
            ),
          )
          as _i2.Rxn<String>);

  @override
  _i2.Rxn<_i5.SubtitleTrack> get currentSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#currentSubtitle),
            returnValue: _FakeRxn_4<_i5.SubtitleTrack>(
              this,
              Invocation.getter(#currentSubtitle),
            ),
            returnValueForMissingStub: _FakeRxn_4<_i5.SubtitleTrack>(
              this,
              Invocation.getter(#currentSubtitle),
            ),
          )
          as _i2.Rxn<_i5.SubtitleTrack>);

  @override
  bool get hasSourceLoaded =>
      (super.noSuchMethod(
            Invocation.getter(#hasSourceLoaded),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_5<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_5<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_5<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_5<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isSameVideo(_i4.MediaItem? item, _i4.MediaVariant? v) =>
      (super.noSuchMethod(
            Invocation.method(#isSameVideo, [item, v]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> play(_i4.MediaItem? item, _i4.MediaVariant? variant) =>
      (super.noSuchMethod(
            Invocation.method(#play, [item, variant]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> toggle() =>
      (super.noSuchMethod(
            Invocation.method(#toggle, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> seek(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> replay() =>
      (super.noSuchMethod(
            Invocation.method(#replay, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setVolume(double? v) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [v]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setSpeed(double? v) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeed, [v]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadSubtitle(_i5.SubtitleTrack? track) =>
      (super.noSuchMethod(
            Invocation.method(#loadSubtitle, [track]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void clearLastItem() => super.noSuchMethod(
    Invocation.method(#clearLastItem, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LocalLibraryStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalLibraryStore extends _i1.Mock implements _i7.LocalLibraryStore {
  @override
  _i6.Future<List<_i4.MediaItem>> readAll() =>
      (super.noSuchMethod(
            Invocation.method(#readAll, []),
            returnValue: _i6.Future<List<_i4.MediaItem>>.value(
              <_i4.MediaItem>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i4.MediaItem>>.value(
              <_i4.MediaItem>[],
            ),
          )
          as _i6.Future<List<_i4.MediaItem>>);

  @override
  _i6.Future<void> upsert(_i4.MediaItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [item]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> remove(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
